"""add tree ownership transfer tracking

Revision ID: 229d9e0d5619
Revises: a9b3c1d5e7f8
Create Date: 2026-06-19 15:14:04.056979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '229d9e0d5619'
down_revision: Union[str, None] = 'a9b3c1d5e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_citations_member_id'), 'citations', ['member_id'], unique=False)
    op.create_index(op.f('ix_citations_source_id'), 'citations', ['source_id'], unique=False)
    op.add_column('trees', sa.Column('previous_owner_id', sa.String(length=36), nullable=True))
    op.add_column('trees', sa.Column('ownership_transferred_at', sa.String(length=40), nullable=True))
    op.create_foreign_key(None, 'trees', 'users', ['previous_owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trees', type_='foreignkey')
    op.drop_column('trees', 'ownership_transferred_at')
    op.drop_column('trees', 'previous_owner_id')
    op.drop_index(op.f('ix_citations_source_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_member_id'), table_name='citations')
    # ### end Alembic commands ###
