"""add locale to legal documents

Revision ID: 2516a8c16809
Revises: b350d7612cc1
Create Date: 2026-06-30 16:05:59.115486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2516a8c16809'
down_revision: Union[str, None] = 'b350d7612cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Per-locale support for legal documents (#519 follow-up): German (`de`)
    # is the authoritative/default legal locale, English (`en`) a secondary
    # translation. Add `locale` with a server_default of 'de' so existing
    # rows (recorded before locales existed) backfill to German — they were
    # in fact accepted/published before this feature existed, and German is
    # the operator's authoritative locale. The server_default is dropped
    # after backfill so the column has no implicit default going forward;
    # the application always supplies `locale` explicitly.
    op.add_column(
        'legal_acceptances',
        sa.Column('locale', sa.String(length=8), nullable=False, server_default='de'),
    )
    op.add_column(
        'legal_document_versions',
        sa.Column('locale', sa.String(length=8), nullable=False, server_default='de'),
    )
    op.alter_column('legal_acceptances', 'locale', server_default=None)
    op.alter_column('legal_document_versions', 'locale', server_default=None)
    op.drop_index(op.f('ix_legal_doc_versions_type_version'), table_name='legal_document_versions')
    op.drop_constraint(op.f('uq_legal_doc_version_type_hash'), 'legal_document_versions', type_='unique')
    op.create_index('ix_legal_doc_versions_type_locale_version', 'legal_document_versions', ['document_type', 'locale', 'version'], unique=False)
    op.create_unique_constraint('uq_legal_doc_version_type_locale_hash', 'legal_document_versions', ['document_type', 'locale', 'content_hash'])
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected the same pre-existing, unrelated drift
    # noted in ccf33bfb674a/b350d7612cc1 (a stale `members.linked_tree_id`
    # column/index/FK with no corresponding model field or migration). Still
    # out of scope for this PR (#519 follow-up); intentionally left untouched
    # here too.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_legal_doc_version_type_locale_hash', 'legal_document_versions', type_='unique')
    op.drop_index('ix_legal_doc_versions_type_locale_version', table_name='legal_document_versions')
    op.create_unique_constraint(op.f('uq_legal_doc_version_type_hash'), 'legal_document_versions', ['document_type', 'content_hash'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_legal_doc_versions_type_version'), 'legal_document_versions', ['document_type', 'version'], unique=False)
    op.drop_column('legal_document_versions', 'locale')
    op.drop_column('legal_acceptances', 'locale')
    # ### end Alembic commands ###
