"""add member deceased flag

Revision ID: 4a2bc8144c1c
Revises: f1a2b3c4d5e6
Create Date: 2026-06-14 20:36:46.955306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2bc8144c1c'
down_revision: Union[str, None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('members', sa.Column('deceased', sa.Boolean(), server_default=sa.false(), nullable=False))
    # Backfill: anyone with a death date is deceased.
    op.execute("UPDATE members SET deceased = true WHERE \"dateOfDeath\" IS NOT NULL AND \"dateOfDeath\" <> ''")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'deceased')
    # ### end Alembic commands ###
