"""add quality issue dismissals table

Revision ID: 5f37813d4464
Revises: v1_3_0_adopted_drop_horizontal
Create Date: 2026-07-01 04:47:14.199462

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f37813d4464"
down_revision: str | None = "v1_3_0_adopted_drop_horizontal"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quality_issue_dismissals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("tree_id", sa.String(length=36), nullable=False),
        sa.Column("issue_id", sa.String(length=64), nullable=False),
        sa.Column("issue_type", sa.String(length=50), nullable=False),
        sa.Column("member_ids", sa.Text(), nullable=False),
        sa.Column("dismissed_at", sa.String(length=40), nullable=False),
        sa.Column("dismissed_by_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(["dismissed_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tree_id"], ["trees.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tree_id", "issue_id", name="uq_quality_dismissal_tree_issue"
        ),
    )
    op.create_index(
        op.f("ix_quality_issue_dismissals_issue_id"),
        "quality_issue_dismissals",
        ["issue_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_quality_issue_dismissals_tree_id"),
        "quality_issue_dismissals",
        ["tree_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_quality_issue_dismissals_tree_id"), table_name="quality_issue_dismissals"
    )
    op.drop_index(
        op.f("ix_quality_issue_dismissals_issue_id"),
        table_name="quality_issue_dismissals",
    )
    op.drop_table("quality_issue_dismissals")
    # ### end Alembic commands ###
