"""add identity link claims (#1014)

Revision ID: a540ee9c5722
Revises: v2_0_0_defer_identity_link_fks
Create Date: 2026-09-06 08:42:29.255596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a540ee9c5722'
down_revision: Union[str, None] = 'v2_0_0_defer_identity_link_fks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_link_claims',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_member_id', sa.String(length=36), nullable=False),
    sa.Column('proposed_by', sa.String(length=36), nullable=True),
    sa.Column('source_approved_by', sa.String(length=36), nullable=True),
    sa.Column('source_approved_at', sa.String(length=40), nullable=True),
    sa.Column('target_user_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.String(length=40), nullable=False),
    sa.Column('expires_at', sa.String(length=40), nullable=True),
    sa.Column('resulting_identity_link_id', sa.String(length=36), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.String(length=40), nullable=True),
    sa.Column('decision_reason', sa.String(length=500), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['proposed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resulting_identity_link_id'], ['identity_links.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_link_claims_source_member_id'), 'identity_link_claims', ['source_member_id'], unique=False)
    op.create_index(op.f('ix_identity_link_claims_target_user_id'), 'identity_link_claims', ['target_user_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also proposed dropping members.linked_member_id /
    # linked_workspace_id (and their index/FKs) and recreating
    # ix_members_name_normalized_trgm. Both are pre-existing drift between
    # this dev DB and the ORM models, unrelated to #1014 — left for a
    # separate migration.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_link_claims_target_user_id'), table_name='identity_link_claims')
    op.drop_index(op.f('ix_identity_link_claims_source_member_id'), table_name='identity_link_claims')
    op.drop_table('identity_link_claims')
    # ### end Alembic commands ###
