"""add legal document versions

Revision ID: b350d7612cc1
Revises: ccf33bfb674a
Create Date: 2026-06-30 15:39:39.352478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b350d7612cc1'
down_revision: Union[str, None] = 'ccf33bfb674a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_document_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('published_at', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', 'content_hash', name='uq_legal_doc_version_type_hash')
    )
    op.create_index('ix_legal_doc_versions_type_version', 'legal_document_versions', ['document_type', 'version'], unique=False)
    op.add_column('legal_acceptances', sa.Column('terms_hash', sa.String(length=64), nullable=True))
    op.add_column('legal_acceptances', sa.Column('privacy_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected the same pre-existing, unrelated drift
    # noted in ccf33bfb674a (a stale `members.linked_tree_id` column/index/FK
    # with no corresponding model field or migration). Still out of scope for
    # this PR (#519 follow-up); intentionally left untouched here too.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legal_acceptances', 'privacy_hash')
    op.drop_column('legal_acceptances', 'terms_hash')
    op.drop_index('ix_legal_doc_versions_type_version', table_name='legal_document_versions')
    op.drop_table('legal_document_versions')
    # ### end Alembic commands ###
