"""add tree membership restrictions

Revision ID: c0a7c7f4314e
Revises: b8d3f4a1c2e9
Create Date: 2026-06-15 21:02:11.031918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a7c7f4314e'
down_revision: Union[str, None] = 'b8d3f4a1c2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tree_memberships', sa.Column('restrictions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tree_memberships', 'restrictions')
    # ### end Alembic commands ###
