"""add legal_acceptances

Revision ID: ccf33bfb674a
Revises: v1_3_0_adopted_drop_horizontal
Create Date: 2026-06-30 14:35:45.143898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ccf33bfb674a'
down_revision: Union[str, None] = 'v1_3_0_adopted_drop_horizontal'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_acceptances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('accepted_at', sa.String(length=40), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_legal_acceptances_user_id', 'legal_acceptances', ['user_id'], unique=False)
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected a pre-existing, unrelated drift on this
    # dev DB volume (a stale `members.linked_tree_id` column/index/FK with no
    # corresponding model field or migration). That drift predates this PR
    # (#519) and is intentionally left untouched here — out of scope.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_legal_acceptances_user_id', table_name='legal_acceptances')
    op.drop_table('legal_acceptances')
    # ### end Alembic commands ###
