"""Aggregate API router."""

from fastapi import APIRouter

from app.api.routes import (
    activity,
    admin_audit,
    auth,
    backups,
    content_scopes,
    documents,
    events,
    export_import,
    friends,
    gallery,
    geocode,
    identity_links,
    invitations,
    jobs,
    legal,
    media,
    member_diseases,
    member_relations,
    members,
    migration,
    notifications,
    oauth,
    preferences,
    presence,
    quality,
    relation_types,
    saved_views,
    search,
    sections,
    settings,
    sse,
    statistics,
    stories,
    tasks,
    users,
    workspace_jobs,
    workspace_public,
    workspace_sharing,
    workspace_transfer,
    workspaces,
)

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(admin_audit.router)
api_router.include_router(oauth.router)
api_router.include_router(users.router)
api_router.include_router(preferences.router)
api_router.include_router(settings.router)
api_router.include_router(friends.router)
api_router.include_router(relation_types.router)
api_router.include_router(relation_types.admin_router)
api_router.include_router(search.router)
api_router.include_router(backups.router)
api_router.include_router(workspaces.router)
api_router.include_router(workspace_public.router)
api_router.include_router(workspace_sharing.router)
api_router.include_router(workspace_jobs.router)
api_router.include_router(workspace_transfer.router)
api_router.include_router(sections.router)
api_router.include_router(saved_views.router)
api_router.include_router(content_scopes.router)
api_router.include_router(invitations.router)
api_router.include_router(invitations.global_router)
api_router.include_router(export_import.router)
api_router.include_router(jobs.router)
api_router.include_router(members.router)
api_router.include_router(member_relations.router)
api_router.include_router(member_diseases.router)
api_router.include_router(identity_links.router)
api_router.include_router(migration.router)
api_router.include_router(migration.admin_router)
api_router.include_router(gallery.router)
api_router.include_router(events.router)
api_router.include_router(geocode.router)
api_router.include_router(stories.router)
api_router.include_router(tasks.router)
api_router.include_router(documents.router)
api_router.include_router(activity.router)
api_router.include_router(presence.router)
api_router.include_router(quality.router)
api_router.include_router(statistics.router)
api_router.include_router(media.router)
api_router.include_router(sse.router)
api_router.include_router(legal.router)
api_router.include_router(notifications.router)
